name: GitHub Metrics

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ron-25
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Costa_Rica
          repositories_affiliations: owner, collaborator, organization_member
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_stars: yes
          plugin_traffic: yes
