name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ron-25
          template: classic
          base: header, activity, community, repositories, achievements
          config_timezone: America/Costa_Rica
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: Ron-25,ronald.gordon@netforemost.com
          plugin_traffic: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_code: yes
          plugin_activity: yes
          plugin_repositories: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_analysis_timeout: 30
