name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ron-25

          base: ""
          template: classic

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_activity: yes
          plugin_activity_limit: 10

          output_action: commit
          committer_branch: main
          filename: github-metrics.svg
